baseURL: 'https://bartvaneynde.github.io/b-etch'
languageCode: en-us
title: Bart's code sniplets
theme: etch
enableInlineShortcodes: true
pygmentsCodeFences: true
pygmentsUseClasses: true
params:
  description: Build with Hugo
  copyright: Copyright © 2024 Bart Van Eynde
  dark: auto
  highlight: true
menu:
  main:
    - identifier: posts
      name: posts
      title: posts
      url: /
      weight: 10
    - identifier: tags
      name: tags
      title: tags
      url: /tags/
      weight: 15
    - identifier: about
      name: about
      title: about
      url: /about/
      weight: 20
permalinks:
  posts: '/:title/'
  tags: '/tmp/tags/'
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    ordered: true
